// Rust Elytra Client

plugins {
    id 'fabric-loom' version '1.17-SNAPSHOT'
    id 'maven-publish'
    id 'java'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}


repositories {
    mavenLocal()
    maven {
        name = "meteor-maven"
        url = uri("https://maven.meteordev.org/releases")
    }
    maven {
        name = "meteor-maven-snapshots"
        url = uri("https://maven.meteordev.org/snapshots")
    }

    // Nether path finder来源
    maven {
        name = 'babbaj-repo'
        url = 'https://babbaj.github.io/maven/'
    }
}

fabricApi {
    configureDataGeneration {
        client = true
    }
}


dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    // 暂时使用yarn mappings,以后迁移到官方映射?
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    modCompileOnly "meteordevelopment:baritone:1.21.11-SNAPSHOT"

    modImplementation "dev.rstminecraft:RustClientCore:1.1-SNAPSHOT",{changing=true }
    include "dev.rstminecraft:RustClientCore:1.1-SNAPSHOT"

    implementation "dev.babbaj:nether-pathfinder:${project.nether_pathfinder_version}"
    include "dev.babbaj:nether-pathfinder:${project.nether_pathfinder_version}"
}



processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

// Java21
tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.named("remapJar") {
    def mcVersion = project.property("minecraft_version")
    def baseName = project.property("archives_base_name")
    def modVersion = project.property("mod_version")
    def buildTime = new Date().format("yyMMdd_HHmm")

    archiveBaseName = "${mcVersion}/${baseName}-${mcVersion}"
    archiveVersion = ("${modVersion}-${buildTime}")
}

tasks.named("remapSourcesJar") {
    def mcVersion = project.property("minecraft_version")
    def baseName = project.property("archives_base_name")
    def modVersion = project.property("mod_version")
    def buildTime = new Date().format("yyMMdd_HHmm")

    archiveBaseName = "${mcVersion}/${baseName}-${mcVersion}"
    archiveVersion = ("${modVersion}-${buildTime}")
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // 暂无上传所需仓库
    }
}

loom{
    accessWidenerPath = file("src/main/resources/rust-elytra-client.accesswidener")
}